OBJS= \
	  EventLog.o \
	  BeaconDeploy.o \
	  PlaneGenerator.o \
	  SimulatorArgument.o \
	  DistanceScenario.o \
	  DistanceSimulator.o \
	  EventGenerator.o \
	  ListenerMover.o \
	  PathGenerator.o \


include ../include.mk
include ../module.mk
